### ISSUE TITLE
dual indexes. 

### ISSUE THREAD

**Issue by raw937** [jfjlaros/demultiplex#1]
Hello, 

For example: In bold dual barcode

#R1 read
@SOLEXA1_0069_FC:3:1:1673:948#ACAGTG/1
GACTAACCGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGAATGTTAGCCGTCGGGCAGTATACTGTTCGG
+
BMMQNTWSWWb_____b_bb__________Y_________YYYYY[[[Y[__________XXRWXVVVVTYYYYYT

#R2 read
@SOLEXA1_0069_FC:3:1:1673:948#ACAGTG/2
CTGAAGGGTTGCGCTCGTTGCGGGACTTAACCCAACATCTCACGACACGAGCTGACGACAGCCATGCAGCACCTGT
+
ghgaggfghhhhhhhhhhghhhhhhhhhhfhhhghfWffch[hhgahhedffddR[^W\^Zc^\\_cac[Wb]^W^

The barcodes are here (16 possible):
TCAG*TCAG
CTGA*CTGA
TCAG*GACT
GACT*GACT
AGTC*AGTC
GACT*TCAG
GACT*AGTC
GACT*CTGA
TCAG*CTGA
AGTC*TCAG
AGTC*GACT
CTGA*AGTC
CTGA*GACT
AGTC*CTGA
TCAG*AGTC
CTGA*TCAG

**Comment by raw937** [comment]
Hello, 
I need it if possible to use dual indexes. 

For example: In bold dual barcode

#R1 read
@SOLEXA1_0069_FC:3:1:1673:948#ACAGTG/1
**GACT**AACCGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGAATGTTAGCCGTCGGGCAGTATACTGTTCGG
+
BMMQNTWSWWb_____b_bb__________Y_________YYYYY[[[Y[__________XXRWXVVVVTYYYYYT

#R2 read
@SOLEXA1_0069_FC:3:1:1673:948#ACAGTG/2
**CTGA**AGGGTTGCGCTCGTTGCGGGACTTAACCCAACATCTCACGACACGAGCTGACGACAGCCATGCAGCACCTGT
+
ghgaggfghhhhhhhhhhghhhhhhhhhhfhhhghfWffch[hhgahhedffddR[^W^Zc^\_cac[Wb]^W^

Here are 16 possible in the file I am working on. 
TCAG-TCAG
CTGA-CTGA
TCAG-GACT
GACT-GACT
AGTC-AGTC
GACT-TCAG
GACT-AGTC
GACT-CTGA
TCAG-CTGA
AGTC-TCAG
AGTC-GACT
CTGA-AGTC
CTGA-GACT
AGTC-CTGA
TCAG-AGTC
CTGA-TCAG

The first four nts are the barcode like our example before would be:
GACT-CTGA_R1.fq
GACT-CTGA_R2.fq

But you would need both reads to tell you that it's GACT-CTGA and not something else. 
What would the command look like for this? Does this demux script do the dual barcoding?

**Comment by raw937** [comment]
How would that work? I feel I don't have the right bacode file. Does it work only on python 3?

**Comment by jfjlaros** [comment]
See the `-r`, `-e` and `-s` options for barcodes that are located in the reads instead of the header.

Indeed, this package only works with Python 3 as of today (some dependencies did not support Python 2 anymore).
