### ISSUE TITLE
How does one set the mismatch, deletion settings?

### ISSUE THREAD

**Issue by rgranit** [jfjlaros/demultiplex#11]
I've looked at the documentation and could not find how does one define the amount or allowed mismatches and deletions.. any advice?

Thanks!

**Comment by jfjlaros** [comment]
To allow for insertions or deletions (disabled by default) the `-d` option should be used. The amount of mismatches (including insertions and deletions, if enabled) is controlled with the `-m` option. 

Interestingly, this is indeed not described in the documentation, I will add it. Thank you for pointing this out.

**Comment by rgranit** [comment]
Thanks! adding this to the documentation would be great. Also when you run `demultiplex --help` it does not suggest these options.

**Comment by jfjlaros** [comment]
That is because these options are specific for the subcommands `demux` and `match`. E.g., when you run `demultiplex demux -h`, you should get a full list of options relevant for that subcommand.

**Comment by jfjlaros** [comment]
Fixed in 4099984921d42c4a141c06c13e496ff633f6b92e.
