### ISSUE TITLE
Working with compressed or piped files

### ISSUE THREAD

**Issue by bulksoil** [jfjlaros/demultiplex#12]
I'm demultiplexing files from several NovaSeq runs. I really like this demultiplex software for its ease of use. But one feature that would be really handy is for the program to read and write compressed data. Having to decompress the file takes up a lot of space and leads to redundancy on the server. Alternatively, reading the sequencing file (at lease for single end) from STDIN could be very helpful as well.

**Comment by ipatop** [comment]
I agree. I actually assumed that it was working in zipped files and got the following error: 
"demultiplex: error: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)"

**Comment by jfjlaros** [comment]
I added support for `gzip` and `bzip2` compressed files. Could you give it a try?
