### ISSUE TITLE
Parallel processing with multiple cores

### ISSUE THREAD

**Issue by lokeshbio** [jfjlaros/demultiplex#13]
I am a new user to this tool and the options for long-read is exactly what I was looking for. However, I didnt find any option to use multiple CPUs/cores that the processes could be run in parallel. This could come really in handy, maybe the tool automatically uses all the processors available?

**Comment by jfjlaros** [comment]
There is currently no support for multi-threading. Do you experience any excessive throughput times?

**Comment by naila53** [comment]
hi @jfjlaros I know this is closed but i wanted to follow up as I'm currently running your method to demultiplex large fastq read1 and read2( 60GB each) on an HPC where i need to separate 5 samples of CITEseq antibodies sequences but it's taking forever, it's been running for 12hours now and still not done..is this normal?
I think multithreading should speed the process.

**Comment by jfjlaros** [comment]
The only thing that comes to mind is to split the input files and process them in parallel.

I understand that this is not very convenient for the end user, but adding threading support does not seem like a good way forward to me. I would rather rewrite this tool in a more performant language.
