### ISSUE TITLE
Cannot demultiplex based on barcode in header

### ISSUE THREAD

**Issue by RominaAugustin** [jfjlaros/demultiplex#14]
I have paired end sequencing data of a NextSeq run.
I want to demultiplex my libraries based on an adapter in the header - since this tool should be able to do this I used this.
I unzipped my fastq-files of read 1 and read 2 and generated a file with the barcodes used. 
I  generated a .txt file which looks like the following example:
adaptername1    sequence1
adaptername2    sequence2
adaptername3    sequence3
--> I am using a textfile because when I am using a .csv file as recommended on the webpage it is not working.

Then I used the demultiplex demux command. The command is running but in the end I only get the UNKNOWN fastq files of read 1 and read 2. 
Is there anything I have missed? 

Thank you!

**Comment by jfjlaros** [comment]
Could you perhaps share one header line and one line of the barcodes file?

**Comment by RominaAugustin** [comment]
yes of course!
So the header looks like this where the bold letters are the index
@NB500883:606:HGKVJBGXG:1:11101:7543:1066 1:N:0:TAAGGCGA+**CTCCTTTC**
And the barcode file looks like this:
p502	CTCTCTAT
I have no column names here - maybe thats already one of the problems? How should my columns be named in the barcode file?

Thank you!

**Comment by jfjlaros** [comment]
It seems that you have a dual index in the header, of which only a part is used for demultiplexing. You can select the relevant part by using the `-s` and `-e` options. In your case, using `-s 10` should do the trick.

**Comment by RominaAugustin** [comment]
Thank you very much! Now its demultiplexing correctly based on the barcodes we used :)

**Comment by jfjlaros** [comment]
The header contains the string `TAAGGCGA+CTCCTTTC` in the index field. By default the program will use this entire string (position 1 to 17) for demultiplexing. By setting the start (`-s`) to 10, everything after the `+` (positions 10 to 17) is used as a barcode. To select the first barcode in this example, the end (`-e`) can be set to 8. A combination of the two options can be used to select an arbitrary substring, e.g., `-s 2 -e 5` will select the substring `AAGG`.

I will add this explanation to the documentation as well.

**Comment by RominaAugustin** [comment]
Thank you for this explanation! Now it is more clear to me 👍 
Yes - this is a great idea to add this to the documentation!
Thank you :)

**Comment by RominaAugustin** [comment]
Hey again!
Since I checked my data I realized there are also reads assignet to a barcode although there is a mismatch of one nucleotide.
Since our barcodes look very different, this shouldnt be a big deal. But - is there a possibility to specifify if and how many nucleotides can mismatch?
Thank you!

**Comment by jfjlaros** [comment]
Yes, that is the core functionality of this tool. In the documentation there is a [section](https://demultiplex.readthedocs.io/en/latest/usage.html#illumina-fastq-files) about specifying the amount of mismatches and allowing for insertions and deletions. Also please read the note in that section about modifying the standard settings.

**Comment by RominaAugustin** [comment]
Okay, thank you for the quick reply - I also realized that there are several closed git issues, some of them seem to be also helpful to me. 
I am sorry I am pretty new to all this bioinformatical data analysis - so I might ask some - so you - redundant questions.

**Comment by jfjlaros** [comment]
No problem.
