### ISSUE TITLE
demultiplex match outputs all input reads to each barcode

### ISSUE THREAD

**Issue by callumparr** [jfjlaros/demultiplex#16]
I am trying to demultiplex some reads that have internal barcodes inserted through restriction digest and then ligation.

I gave the full length of the bridge adapter containing the barcodes so they share some common sequences across them but differ at barcode sequence of course:

```
name,seq 
barcode1,DpnII-BC1(sense orientation)-EcoR1-BC1(revcom)
barcode2,DpnII-BC2(sense)-EcoR1-BC2(revcom)
....
....
....

```
```
KVII_F_R_1,GATC**GAGCTCGA**GAATTC**TCGAGCTC**GATC
```
When I run it assigns all the input reads to each of the output FASTQ files.I am unsure if I am misunderstanding something or doing something very wrong. I tried supply just the 8nt index in barcode file but it is doing the same thing. 

demultiplex match barcodes.csv reads.fastq

**Comment by jfjlaros** [comment]
If you know the exact location of the barcode, then you should use the `demux` subcommand instead of `match`. Please see the [documentation](https://demultiplex.readthedocs.io/en/latest/usage.html#other-files) for more information.

**Comment by callumparr** [comment]
Sorry I did not explain well. The barcoding system is following combinatorial indexing scheme used in sci-HiC library prep but for a different purpose and therefore I cannot use their means to demultiplex so was wanting to try your tool that can use match to first align and then demultiplex. The barcodes are ligated at restriction sites which are then embedded at multiple but unknown locations as the genomic fragments are stitch together through in situ proximal ligation assay. 

Anyway, I think it is working, just the documentation is incorrect to say to use a .csv file. 

Thank you.

**Comment by Ruismart** [comment]
save issue .. actually it should be a .tsv file , haha ~
