### ISSUE TITLE
dealing with conflicts

### ISSUE THREAD

**Issue by callumparr** [jfjlaros/demultiplex#17]
Judging by the no. of reads in each barcode FASTQ output it would seem reads may be assigned to multiple barcodes. I am guessing that conflicts are ignored? 

Is there a way to output a file showing the mappings of reads to barcode FASTQs to easily check multi assignments

**Comment by jfjlaros** [comment]
The `match` subcommand assigns a read to all barcodes that match, the `demux` subcommand will assign a read to only one barcode. I am not sure what you mean by conflicts.

If you want to check to which barcodes a read is assigned, I would suggest to take the header of the read and use `grep -l` on the output files.

**Comment by callumparr** [comment]
I was more interested in using match that allows demultiplexing where the barcode is at an unknown location in the read rather than being able to supply multiple indices per sample. I expect to see only one type of barcode per read although it is possible to have multiple copies of this barcode in each of my long-reads.

Is there way for match to find the barcode(s) and output only one assignment based on best similarity score?

**Comment by jfjlaros** [comment]
Not at the moment, but I could look into it.

Perhaps you could try to extend your barcodes by adding stable flanking sequences. This will increase the specificity of the demultiplexing a lot.

**Comment by jfjlaros** [comment]
I wonder whether this issue is resolved now. Do you expect any action from me?

**Comment by callumparr** [comment]
Ah yes sorry can consider closed. I will experiment a little with the flanking regions. Thank you for your reply
