### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by Kevin-Brockers** [jfjlaros/demultiplex#18]
Dear all,

is there a way to specify an output directory for the demultiplexed files?

All best and thanks in advance,
Kevin

**Comment by jfjlaros** [comment]
Currently not, but it should not be difficult to add this.

**Comment by jfjlaros** [comment]
I added the command line option `-p` to the `demux` and `match` subcommands. Can you give it a try?

**Comment by Kevin-Brockers** [comment]
Sure I gave it a try, see below.

I want to integrate it in a snakemake workflow and I appended the error it gave me:
Potentially a follow up question: does demultiplex demux handle fq.gz files or should I decompress them before?

Thanks for your help!
All best,
Kevin

---
[Sat Mar  6 22:51:32 2021]
rule demultiplex_fastq:
    input: ../data/fastq/umi_extracted/MUC21057_1.umi_extracted.fastq.gz, ../data/fastq/umi_extracted/MUC21057_2.umi_extracted.fastq.gz, ../data/temp/alignment/indices.tsv
    output: ../data/fastq/demultiplexed
    jobid: 3

usage: demultiplex [-h] [-v] {guess,demux,match} ...
demultiplex: error: invalid output directory
[Sat Mar  6 22:51:32 2021]
Error in rule demultiplex_fastq:
    jobid: 3
    output: ../data/fastq/demultiplexed
    shell:
        demultiplex demux -r -e 6 -m 0 -p ../data/fastq/demultiplexed ../data/temp/alignment/indices.tsv ../data/fastq/umi_extracted/MUC21057_1.umi_extracted.fastq.gz ../data/fastq/umi_extracted/MUC21057_2.umi_extracted.fastq.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by jfjlaros** [comment]
My guess is that the command fails because the output directory does not exist.

There is support for gzip and bzip2 compressed files in the development version (which you are using).

**Comment by jfjlaros** [comment]
I just added automatic directory creation.

**Comment by Kevin-Brockers** [comment]
Please excuse the late reply, I took a day off.

I just started the demultiplexing and yes it's working now. I didn't thought about creating a output dir before :D Sorry for that but your automatic directory creation also works fine.

Thanks a lot for the help!

**Comment by Kevin-Brockers** [comment]
The output directory specification works well!

I assume you will implement it in the future but gzip outputs would be great ;) 

All best,
Kevin

**Comment by jfjlaros** [comment]
The output format follows the input format. So if you supply gzipped inputs, the outputs will be gzipped as well.

**Comment by Kevin-Brockers** [comment]
Okey that's wired, because I just verified that the input file is a fastq.gz 'gzip -cd | head' worked well. Whereas the demultiplexed outputs are not gzipped, sizewise and if I try to run the command above it gives the error that the file is not gzipped

**Comment by jfjlaros** [comment]
I see what you mean. Apparently my previous statement was incorrect. I will have a look at it.

**Comment by jfjlaros** [comment]
It turned out that this functionality was only half implemented. It should work now.

Perhaps you can give it a try?

**Comment by Kevin-Brockers** [comment]
Sure, I will do that within the next days and give you an update. 
All best,
Kevin
