### ISSUE TITLE
tags 5' and 3' in two different files usage

### ISSUE THREAD

**Issue by iadamo1** [jfjlaros/demultiplex#19]
Hi,

I am trying to demultiplex Illumina fastq files R1 and R2 and I have two files for the tags: 
forward tags: 
gITS7_tag_41;CCACGTCACT
gITS7_tag_42;CCACTATCGT
gITS7_tag_44;CCAGATACTT
gITS7_tag_4;CACATAGTCT
and reverse:
ITS4a_tag_41;CCGACTGTC
ITS4a_tag_42;CCGATACTG
ITS4a_tag_44;CCGCTATAC
ITS4a_tag_4;CACATGTCG

how can I use these two files to demultiplex my fastq files?
thanks a lo!

**Comment by jfjlaros** [comment]
Please have a look at the [FAQ](https://demultiplex.readthedocs.io/en/latest/faq.html). Do not hesitate to contact me if anything is unclear.
