### ISSUE TITLE
demultiplexing illumina with forward and reverse tag 

### ISSUE THREAD

**Issue by iadamo1** [jfjlaros/demultiplex#22]
Hi,

I would like to demultiplex Illumina sequences of the ITS2 region. The barcodes are in the head of the sequence and I have two separated files gITS7 which is forward and ITS4 which is the reverse. Could you please tell me how to deal with two barcodes files, one containing the forward tags and the other the reverse? 

Thanks a lot!

**Comment by jfjlaros** [comment]
I think this question is covered in the first section of the [FAQ](https://demultiplex.readthedocs.io/en/latest/faq.html).
