### ISSUE TITLE
positions for barcodes do not work at all!

### ISSUE THREAD

**Issue by antonkulaga** [jfjlaros/demultiplex#23]
The version in pip does not seem to work at all! I manually checked barcodes and they exist, but I get everything UNKNOWN for:
```
demultiplex demux -r -s 3 -e 9 barcodes.txt S3987Nr1.1.fastq S3987Nr1.2.fastq 
```

[barcodes.txt](https://github.com/jfjlaros/demultiplex/files/6927528/barcodes.txt)

[Uploading
[S3987Nr1.2_sample4-n10000.fastq.txt](https://github.com/jfjlaros/demultiplex/files/6927522/S3987Nr1.2_sample4-n10000.fastq.txt)
 S3987Nr1.1_sample4-n10000.fastq.txt…]()

**Comment by jfjlaros** [comment]
It seems your barcodes are of length 9 and have wildcards (`N`s) in them, yet you select seven nucleotides from the read.

Perhaps you can try to remove the three `N`s from your barcodes and select six nucelotides from the read (e.g., `-s 4 -e 9`).
