### ISSUE TITLE
Degenerated constructs

### ISSUE THREAD

**Issue by iquasere** [jfjlaros/demultiplex#24]
Greetings!

I was wondering if demultiplex can work with degenerate constructs, e.g. ```TTMTRGRACAGGCTCCTC```.

**Comment by jfjlaros** [comment]
I think it will work, but since the internal aligner has no notion of this, comparing a degenerate base to one of its possibilities will result in a mismatch. E.g., `N` vs. `A` will result in a mismatch, just like `T` vs.. `A` will.

**Comment by iquasere** [comment]
Thank you for clarifying! Also, does demultiplex support multithreading?

**Comment by jfjlaros** [comment]
I am afraid it does not.

**Comment by iquasere** [comment]
Thank you for the informations!

**Comment by jfjlaros** [comment]
You're welcome.
