### ISSUE TITLE
All reads go into unknown

### ISSUE THREAD

**Issue by Phagee** [jfjlaros/demultiplex#26]
Hi jfjlaros, I've got an issue that I can run the command successfully, but all my reads go into unknown.

My barcode is in the sequence, so I ran the command "demultiplex demux -r -s 1 -e 1"

My barcode file looks like this:
inline1	ACTGCGAA
inline7	ACTCCTAC

My fastq file is: 
@M01065:233:000000000-CT4R7:1:1102:19932:1263 1:N:0:ATCACG
A**ACTGCGAA**GGACTACTCGGGTTTCTAATCCTGTTTGCTCCCCACGCTTTCGCACCTGAGCGTCAGTCTTTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTCCAGATATCTACGCATTTCACTGCTACACGTGGAATTCTACCCCCCTCTGACACACTCTAGCCGTGCAGTCACAAATGCAATTCCCAGGTTGAGCCCGGGGATTTCACATCTGTTTTACACAACCGCCTGCGCACGCTGTACGCCCAGTAATTCCGGTTAACGCTTGCACCCTCCGTATTACCGCGGCGGCTGACA
+
CCCCCGGGGGGFGGFG9FFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGG7FGGFGGGGGEFEE<AEGGGGGFGGD@=CFGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGCECGGGGGGGGCEFGGGGGGFDGFGGGGGGGGGFF9<D>FF?FEGC9CCCF8<FFGF>C47<FGGGFCAFGGGGGGEFFGEGC:(1:>A7C@C3<FC+40++:.=FG:>>FB?:>4(4996::<97893:6():=89<:*29:2);81+27))4(4:(,-.(.))94907()((-4:@0

Thanks.

**Comment by jfjlaros** [comment]
You only select one nucleotide from the read (from position 1 to 1). The highlighted section is from position 2 to 9, so using `-s 2 -e 9` on the command line should select what you want.

**Comment by Phagee** [comment]
Thanks for your answer. I mistype the question. I actually used "demultiplex demux -r -s 1 -e 12", but it doesn't work. I don't think the problem is with the command line. Are there any other places that can go wrong?

**Comment by jfjlaros** [comment]
Even with `-s 1 -e 12`, you select 11 nucleotides from the read, but your barcodes are of length 8.

**Comment by Phagee** [comment]
I tried and it worked! Thank you so much.
