### ISSUE TITLE
pairwise2.py doesn't work. Biopython deprecated it.

### ISSUE THREAD

**Issue by Yyeserin** [jfjlaros/demultiplex#29]
Hello,

I have installed Demultiplex 1.2.2  in linux using the codes below. My  account is in a cluster.

**git clone https://github.com/jfjlaros/demultiplex
cd demultiplex
pip install .**

I run the code below:
 **demultiplex  guess -o Hrp_barcodes_i7_demultiplex --format=x -n 1000 clean_HRP_Pooled_R1.fastq**

Then I get this error:

**/home/yeserin/.local/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.**

I tried to install the software using python 3.6 instead. But the problem remains. 

I really need to use your software. I couldn't find a good alternative. How can I solve the problem? Do I need to install **Bio.Align.PairwiseAligner**? Then, which document should I modify for _Demultiplex_ to use **_Bio.Align.PairwiseAligner_** instead of **_pairwise2.py_**

Thanks,
Yeserin.

**Comment by jfjlaros** [comment]
There was a problem with one of the dependencies which should be solved now.

A fresh install should install the updated dependency.

**Comment by Yyeserin** [comment]
Thank you for the quick reply. Installation with "_pip install demultiplex_" works now. "_git clone...._" option produced the same issue.

**Comment by Yyeserin** [comment]
Hi again,

I got back to the software again. 

I have another problem now: **parent package.** 

My script is 
 _python demultiplex.py  guess -o ../../Hrp_barcodes_i7 t 2 -n 1000 ../../1header_UC2881_concat_R1.fastq.gz_

The error:

_Traceback (most recent call last):
  File "/crex/proj/snic2022-23-181/pond/demultiplex_snpseq00160/demultiplex/demultiplex/demultiplex.py", line 13, in <module>
    from .match import multi_align
ImportError: attempted relative import with no known parent package_

I don't know much about programming. But some websites say that changing "from" to "import" solves the problem. Should I modify the match.py and demultiplex.py documents?

Thanks!
Yeserin.

**Comment by jfjlaros** [comment]
If the package is properly installed, it should be run as `demultiplex`, not `python demultiplex.py`.

Alternatively, you can go to the parent directory and run `python -m demultiplex.cli`.
