### ISSUE TITLE
Does demultiplex pick up where it left off? 

### ISSUE THREAD

**Issue by jzehnpfennig** [jfjlaros/demultiplex#30]
**Before you start**

Please check the following resources:

- The [Frequently Asked Questions](https://demultiplex.readthedocs.io/en/latest/faq.html).
- Previously answered [questions](https://github.com/jfjlaros/demultiplex/issues?q=is%3Aissue+is%3Aclosed+label%3Aquestion).

**Asking a question**

Please explain what the goal is and describe which steps were taken to reach this goal.

If possible, provide a snippet of:

- The barcodes file.
- The FastQ or Fasta input file.

Most importantly, specify where the barcode is expected to be (in the header,
in the read, etc.).

I am running demultiplex as a job on an HPCC cluster. The job time limit was set to 25 hours and it is about to max out and stop running the job. Will demultiplex pick up where it left off if I resubmit the same job script and have it continue demultiplexing or should I delete the output files and restart the job with a longer time limit? 

Thank you in advance!

**Comment by jfjlaros** [comment]
This program has no functionality to resume terminated jobs, so I am afraid you have to restart it.
