### ISSUE TITLE
Demultiplex with i7 index on dual index FASTQ

### ISSUE THREAD

**Issue by agos316** [jfjlaros/demultiplex#34]
I am trying to demultiplex the FASTQ data with just the i7 index. The library is dual index and the BCL data is no longer available. Is this something I can accomplish using this application ?

Example

Index on read
CCGCTAGCGG+TGCATGGCCA

Want to demux only by 

CCGCTAGCGG on the barcodes.csv sheet. 

There are 1000's of unique i5 reads and I want them binned just to the limited i7 indexes.

**Comment by jfjlaros** [comment]
You could use the `-s` and `-e` command line options to specify where the barcodes start and end respectively. In this case, adding `-e 10` should do the trick.

**Comment by agos316** [comment]
@jfjlaros Thank you for your help, that fixed it for me
