### ISSUE TITLE
demultiplex does not find any barcodes if -e NUM is larger than lenghth of the shortest actually provided barcode in a TSV file

### ISSUE THREAD

**Issue by mmokrejs** [jfjlaros/demultiplex#35]
Hi,
  I probably misunderstood the sparse documentation and used `demultiplex demux -d -m 4 -r -e 22` to search for `16` to `19` nt long barcodes followed by a primer sequence. Everything ends up up in `UNKNOWN`. It seems I can only run `demultiplex demux -d -m 4 -r -e 16` if the shortest provided sequence in the `TSV` file is 16 nt long. I think it is a bug.

  It is unclear what does `demultiplex demux -r` alone without `-s START -e STOP`, please improve the manual at least. The `-h` runtime option provides merely nothing useful either.

Thank you,

**Comment by jfjlaros** [comment]
If I understand you correctly, you have a set of barcodes that differ in length, reside at the start of the read and are followed by a known primer sequence. If this is indeed the case, my suggestion would be to extend the shorter barcodes using the primer sequence, after which you can run the following command:

    demultiplex demux -r -e 19

> It is unclear what does `demultiplex demux -r` alone [...]

From the [documentation](https://demultiplex.readthedocs.io/en/latest/usage.html#other-files): "[...] the `demux` subcommand can be instructed to look for the barcode in the read with the `-r` option and a selection can be made by providing a start- and end coordinate via the `-s` and `-e` options."

If no selection is made, the whole read is used as the barcode.

**Comment by mmokrejs** [comment]
> If I understand you correctly, you have a set of barcodes that differ in length, reside at the start of the read and are followed by a known primer sequence. If this is indeed the case, my suggestion would be to extend the shorter barcodes using the primer sequence, after which you can run the following command: demultiplex demux -r -e 19

Actually vice-versa. The barcodes are 8nt but the primer is 8 or 11 nt long. I can shorten the trailing primer sequence so the whole length would be 16 nt but `demultiplex` should print a warning or be smart enough and handle that situation. Yes, the sequence should start at the very beginning of the read or be at the very end.

So I can run `demultiplex demux -r -e 16` what what does the `-r` mean? Does it scan for a match anywhere inside the read instead of just very beginning or very end?

Please note I use `-d` so hence I assume `-s 1 -e 22` should enable the search to match even 3 insertions not at the very left or very right, as we uncovered previously in issue #33 . So the `-r` is really confusing.

> If no selection is made, the whole read is used as the barcode.

Huh? "Whole read is used as the barcode?" You mean the sequence parsed from `TSV` file is used as the barcode? I am lost. Why do I need `-r` if I omitted `-s X -e Y` because the default search is anchored to very beginning `^` or very end? `$`

I read the documentation and that is why I opened this issue.

**Comment by jfjlaros** [comment]
> The barcodes are 8nt but the primer is 8 or 11 nt long.

In that case, you can simply use the actual barcode in the `barcodes.tsv` file and use the command:

    demultiplex demux -r -e 8

You can do something similar for barcodes that reside at the end of the reads, e.g., when the read length is 100, you can do the following:

    demultiplex -r -s 93 -e 100

I presume you want to use a separate demultiplexing run for this, using the reverse complements of the barcodes.

> Does it scan for a match anywhere inside the read instead of just very beginning or very end?

As explained above, this uses the read as the barcode, the `-s` and `-e` options are used to select a specific part of the read when needed. So `-r -s 10 -e 17` tells the program that the barcode can be found in the read between positions 10 and 17.

> I assume `-s 1 -e 22` should enable the search to match even 3 insertions not at the very left or very right

This selects the first 22 nucleotides of the read, so in your original setup I would expect that only the barcodes of length 18 and higher have a chance of being matched.

I would not recommend this approach though, since such a large edit distance will give many false positive matches. Instead use the approach described above (use 8 nucleotide barcodes).

> You mean the sequence parsed from `TSV` file is used as the barcode?

Yes, this file should contain the barcodes used in the sequencing experiment.

> Why do I need `-r` if I omitted `-s X -e Y` because the default search is anchored to very beginning `^` or very end? `$`

If you omit `-s` and `-e`, then the program is told that the entire read is a barcode. This is quite common when sequencing unique molecular identifiers (a type of barcode).

**Comment by mmokrejs** [comment]
So it happened to me again that I ran `-d -m 4 -r -e 30` which took almost 7 days on a single CPU core and found no barcodes. The reason is I forgot to chop the variable length barcodes (13 or 15nt) followed by the following primer (25 or 26nt) to `30` in total.
I do not understand why `demultiplex` does not raise an error if the input TSV has longer sequences. I can chop them manually but truly said, why cannot `demultiplex` do this on the fly?
Still I do not understand why providing a longer "barcode" sequence than `-e 30` results in no barcodes found at all. My assumption is it will lok for first 30 nt in the FASTQ reads and obviously, parse out 30nt from the TSV sequences.

Now, the bad thing is some samples were aplified only by primers lacking a specific barcode. This forces me to shrink the searching width to 26.

**Comment by jfjlaros** [comment]
In this case, I would make a library containing barcodes of length 15 by adding 2 nucleotides of the primer sequence to the shorter barcodes. Demultiplexing can then be done using `-d -r -e 15`.

As mentioned before, allowing for many mismatches to allow for barcodes of variable length is a bad approach in general. This can only work if each barcode has a large pairwise distance (in this case 9) to every other one. This is unlikely to be the case.

The program does not abort when longer barcodes are provided simply because this may be a use case.

> [...] and obviously, parse out 30nt from the TSV sequences.

It is not clear which ones to select, some may require the prefix, others the suffix or an infix. That is why it must be given explicitly.

**Comment by mmokrejs** [comment]
Thank you for your quick answer.

> It is not clear which ones to select, some may require the prefix, others the suffix or an infix. That is why it must be given explicitly.

I am fine with that as long as `demultiplex` bails out after parsing the input TSV files and realizing the input barcodes have variable length. You did not describe the theoretical use case, for me the program is enforcing a fixed barcode size on either aplicon end. `demultiplex` should be dynamic enough and accept the TSV file with barcodes as I provided them (with variable lengths).

I am not certain you can cope with users assumption that one barcode series is 13nt and adjacent is 15nt (first on 5'-end at the start of R1 and the latter on 3'-end hence at the start of R2) but unfortunately due to unstranded lab design user needs (like me) to check for 15nt on R1 start and for 13nt on R2 start.

Either way, sanity check is missing. yes, I do run `demultiplex` in four sweeps to unleash the forward and reverse barcodes and the swapped insert in the sequencing products. Still it seems the sequences to be searched for must be of equal size in all four attempts.

Hmm, I think that `-m 4` is still justified in my case as the 13 nt and 16 nt barcodes were designed for edit distance I think 6 but I would need to check myself. They are just padded by the following primer sequence and indeed, the 4 edits could in theory be solely located in the padding region (part of the primer).

**Comment by jfjlaros** [comment]
> You did not describe the theoretical use case, [...]

To give an example, barcodes could be present at the end of a fixed length read. If the sample contains insertions, the barcode will be shorter than expected. I am sure our colleagues in the lab can come up with more examples.

> `demultiplex` should [...]

Instead of discussing what you think this program should do, we could also analyse your experimental setup to come up with an approach that fits with what this program is designed for. From the information you shared so far, I think a two step approach may do the trick.

> Hmm, I think that `-m 4` is still justified [...]

You may want to check out this [barcode](https://barcode.readthedocs.io/en/latest/index.html) generator and checker.

**Comment by mmokrejs** [comment]
> > You did not describe the theoretical use case, [...]
> 
> To give an example, barcodes could be present at the end of a fixed length read. If the sample contains insertions, the barcode will be shorter than expected. I am sure our colleagues in the lab can come up with more examples.

Unfortunaly this scenario is not supported, this is why I opened this initially. If any of the barcode provided differs from the `end - start + 1` as provided on the cmdline parameters, it is skipped.

```
JZ71_WU_F    GCCCCTCTGTACAAGT
JZ72_WUAN_F  TAGTCATCGTACAAGT
JZ73_WUA_F   CCGTGGGTGTACAAGT
JZ74_WUME_F  TAAGTAGAGTACAAGT
JZ75_WUMN_F  GCAACGTGGTACAAGT
JZ81_BR_F    AACTTTACATGGCACA
JZ82_BRRE_F  ACTAGGCGATGGCACA
JZ83_BRRN_F  ATTTGCACATGGCACA
JZ84_BRDE_F  AATGCATGATGGCACA
JZ85_BRDN_F  CTTTTTATATGGCACA
JZ104_RY_F   ACGCAATCGTAGAGGA
JZ105_RYAE_F TATCCACTGTAGAGGA
JZ106_RYAN_F AATCAGGGGTAGAGGA
JZ107_RYRE_F GCTGCCTTGTAGAGGA
JZ108_RYRN_F AGTTAGTAGTAGAGGA
JZ114_SA_F   GACAGCCCGGATCTAGT
JZ115_SARE_F AGCACGGTGGATCTAGT
JZ116_SARN_F ATGTTGTCGGATCTAGT
JZ117_SADE_F CTCCCCGCGGATCTAGT
JZ118_SADN_F TATGGCAGGGATCTAGT
JZ124_OM_F   AGATGAGTCTGGTAGC
JZ125_OMDE_F ATCGTACACTGGTAGC
JZ126_OMDN_F TTCTATCCCTGGTAGC
JZ127_OMAE_F CAGGTCGCCTGGTAGC
JZ128_OMAN_F CGGAATTGCTGGTAGC
```

For example, `demultiplex demux -d -m 0 -r -e 16` from the above barcodes skipped all JZ114 to JZ118 because they were mistakenly one nucleotide longer (I padded them by a primer on the right side and included one nucleotide too much).

> 
> > `demultiplex` should [...]
> 
> Instead of discussing what you think this program should do, we could also analyse your experimental setup to come up with an approach that fits with what this program is designed for. From the information you shared so far, I think a two step approach may do the trick.

We can but that would be for another `Issue`. If `demultiplex` does not ignore the extra trailing nucleotides in the input (which I would be fine with) then it should report at least a warning that it is going to find NOTHING for those cases. My preference would be a hard error.

> 
> > Hmm, I think that `-m 4` is still justified [...]

I ended up writing a shell script running demultiplex 39x with `-m 0` to `-m 4` for the `fwd` and `rev` barcodes and searches  at `R1.start()` and `R2.start()` for them. The more relaxed search acts only on those `*_UNKNOWN.fastq` from a previous level. But that is indeed for another `Issue`.

> 
> You may want to check out this [barcode](https://barcode.readthedocs.io/en/latest/index.html) generator and checker.

**Comment by jfjlaros** [comment]
> For example, `demultiplex demux -d -m 0 -r -e 16` from the above barcodes skipped [...]

That is because no mismatches are allowed (`-m 0`).

> [...] because they were mistakenly one nucleotide longer [...]

The next person prepends a nucleotide by mistake, so ignoring part of the input does not seem like a good solution to me.

> [...] it should report at least a warning that it is going to find NOTHING for those cases.

That is not a given. It depends on the number of allowed mismatches.

I do agree that having barcodes of different length is probably rare when using the `demux` method, so perhaps a warning is indeed in order. I will give it some more thought.

> [...] running demultiplex 39x with `-m 0` to `-m 4` [...]

If the set of barcodes is the same as the one you shared, then the maximum edit distance is 1. Some pairs (e.g., `TAAGTAGAGTACAAGT` and `TAGTCATCGTACAAGT`) have an edit distance of less than 5, so correcting for 2 mismatches is not possible in all cases.

**Comment by mmokrejs** [comment]
> > For example, `demultiplex demux -d -m 0 -r -e 16` from the above barcodes skipped [...]
> 
> That is because no mismatches are allowed (`-m 0`).

But not even using `-d -m 1` and so on they were not found.

> 
> > [...] because they were mistakenly one nucleotide longer [...]
> 
> The next person prepends a nucleotide by mistake, so ignoring part of the input does not seem like a good solution to me.

That was just my mistake when creating a TSV file for `demultiplex` with barcode defintions padded on the right side with part of the primer.

> 
> > [...] it should report at least a warning that it is going to find NOTHING for those cases.
> 
> That is not a given. It depends on the number of allowed mismatches.

I have no other explanation why not even `-d -m 4` found any single of those.

> I do agree that having barcodes of different length is probably rare when using the `demux` method, so perhaps a warning is indeed in order. I will give it some more thought.
> 
> > [...] running demultiplex 39x with `-m 0` to `-m 4` [...]
> 
> If the set of barcodes is the same as the one you shared, then the maximum edit distance is 1. Some pairs (e.g., `TAAGTAGAGTACAAGT` and `TAGTCATCGTACAAGT`) have an edit distance of less than 5, so correcting for 2 mismatches is not possible in all cases.

They were not ideal and were designed for `editdistance` but I use `Levenshtein` distance from `demultiplex` to detect them. Yes, the padding by the primer on the right side seems to bring nothing but importantly, this ensures the barcode is detected in front of the primer, which is important.


Here are the counts of detected barcodes with increasing `-d -m $NUM`. Provided the wrapper script starts with `-m0` the mis-detection of a barcode (index hopping) is not so prone to happen, IMO:

```
              count using -d -m 0  count using -d -m 1  count using -d -m 2  count using -d -m 3  count using -d -m 4
JZ71_WU_F                  407262                  681                 1489                   39                  224
JZ73_WUA_F                 476204                  882                 1028                   18                  214
JZ74_WUME_F                381180                  383                  964                    9                  194
JZ75_WUMN_F                247070                  280                  653                   16                  110
JZ81_BR_F                  694807                 1671                 2663                   45                  681
JZ82_BRRE_F                520541                  627                 1154                   14                  211
JZ83_BRRN_F               1014510                 1500                 1625                   23                   73
JZ84_BRDE_F                408407                 1217                 3052                   46                  511
JZ85_BRDN_F                390293                 1426                 3132                   58                  385
JZ104_RY_F                 215074                  658                 2310                   54                  171
JZ105_RYAE_F               502129                  384                 1381                   44                   82
JZ106_RYAN_F               320600                  590                 1386                   31                  107
JZ107_RYRE_F               275391                  702                 2476                   37                  376
JZ108_RYRN_F               489274                  998                 2122                   45                  293
JZ114_SA_F                 337060                  268                  589                    7                  181
JZ115_SARE_F               451946                  713                 1280                   31                  238
JZ116_SARN_F               536160                  919                 1686                   22                  149
JZ117_SADE_F               358396                  596                 1579                   23                  658
JZ118_SADN_F               393186                  553                 2078                   11                  425
JZ124_OM_F                 900801                 1370                 4128                   80                  733
JZ125_OMDE_F               368035                  794                 2187                  104                  227
JZ126_OMDN_F               562646                  665                 2258                   39                  183
JZ127_OMAE_F               435882                  702                 3456                   71                  512
JZ128_OMAN_F               388946                 1553                 2244                   90                  350
```

**Comment by jfjlaros** [comment]
> But not even using `-d -m 1` and so on they were not found.

I tested this on the [test dataset](https://github.com/jfjlaros/demultiplex/blob/master/data/demultiplex.fq) using the following barcodes.

```txt
barcode1 AAAAA
barcode2 ACCCC
barcode3 AGGGG
barcode4 ATTTT
```

The output is as expected:

```bash
$ demultiplex demux -r -e 4 -d -m 1 -p out bc.txt demultiplex.fq
$ ls out/
demultiplex_barcode1.fq  demultiplex_barcode2.fq  demultiplex_barcode3.fq  demultiplex_barcode4.fq
```

> I have no other explanation [...]

Me neither. Without your data, the barcodes, the exact command line invocation and a full description of the experimental setup,  I can only guess.
