### ISSUE TITLE
All reads go into unknown

### ISSUE THREAD

**Issue by wya97** [jfjlaros/demultiplex#36]
Hi jfjlaros, I've got an issue that I can run the command successfully, but all my reads go into unknown.

My barcode is in the header, so I ran the command `demultiplex demux --format=umi -s 41 -e 48`

My barcode file looks like this:
```txt
sc1     AACGTGAT
sc2     AAACATCG
sc3     ATGCCTAA
```

My fastq file is: (the barcode is in 8 nt from 41 to 48 in the header, like `AGCAGGAA`)
```txt
@LH00544:91:22FY3WLT4:5:1101:48631:1056_AGCAGGAA_AGTAGATT 1:N:0:TNATAACC+TNGATATC
AAGNAGTGGTATCAACGCAGAGTACATGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAGAAAAAAACAACACAC
+
III#IIIIIIIIIIIIIIIIII-IIIIIIII9IIIII9IIII9II9I-9I999II9III99999-II-IIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIIII99II9II99IIIIIIIIIII9III9II-I-I-99III--------
@LH00544:91:22FY3WLT4:5:1101:27130:1070_AGCAGGAA_TAGATGTA 1:N:0:TNATAACC+TNGATATC
TGCNAAACTGGAACAGTTTACTACCATGAATCTTTCCTATGTCTTCATTCCTTTATGGGCCTTACTGGCTGGCGCTCTAACAGAACTTGGATATAATGTCTTTTTTGTGAGAGACTGACCTCCGAGTACATCGTCTCATTTCTGTTGCTG
+
I9I#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
```

Thanks!

**Comment by jfjlaros** [comment]
When the UMI format is selected, the parser will use the last field of the description for demultiplexing. For the first read in the example you gave this would be `1056_AGCAGGAA_AGTAGATT`. The selection is done relative to this field, not the entire header. So if you want so select the first barcode from this field, try `-s 6 -e 13`.

I hope that the integer in this field (`1056` in this case) has a fixed number of digits.

**Comment by wya97** [comment]
I tried and it worked! Thank you so much!
