### ISSUE TITLE
Demultiplexing not working?

### ISSUE THREAD

**Issue by ViriatoII** [jfjlaros/demultiplex#4]
Hey,
Maybe I got something wrong, but it's not demultiplexing my fasta file.  I have a big file of pacbio reads, with Pacbio primers + individual barcode. I formated it as follows in a barcodes.csv:

```
D408 GCAGTCGAACATGTAGCTGACTCAGGTCACCACATATCAGAGTGCGGGTAGT
FAP1360A GCAGTCGAACATGTAGCTGACTCAGGTCACACACACAGACTGTGAGGGTAGT
Ky226 GCAGTCGAACATGTAGCTGACTCAGGTCACACACATCTCGTGAGAGGGTAGT
P092 GCAGTCGAACATGTAGCTGACTCAGGTCACCACGCACACACGCGCGGGTAGT
W64A GCAGTCGAACATGTAGCTGACTCAGGTCACCACTCGACTCTCGCGTGGTAGT
```

(I erased the reverses, but am not sure if your program automatically reverses barcodes)
Then run:
`demultiplex demux barcodes.csv myinput.fasta -r `

I only get one input: myinput_UNKNOWN.fasta with all the reads. Whats wrong? I've also trying running it with only one barcode in the .csv file. Same problem.

Cheers,

**Comment by jfjlaros** [comment]
The command you use assumes that the barcode is at a fixed position in the read, the location of which can be specified using the `-s` and `-e` options.

I assume though, that your barcodes are not at a fixed position, for these cases the [`match`](https://demultiplex.readthedocs.io/en/latest/usage.html#barcodes-at-unknown-locations) command can be used. This command indeed also checks the reverse complement.

**Comment by ViriatoII** [comment]
It works! Thank you for the swift reply! 

By the way, are the barcodes removed from the demultiplexed sequences?

**Comment by jfjlaros** [comment]
No, the reads remain unchanged.

**Comment by ViriatoII** [comment]
Thanks! Have a nice day.
