### ISSUE TITLE
demultiplex: error: invalid barcodes file format

### ISSUE THREAD

**Issue by majogomezhughes** [jfjlaros/demultiplex#7]
Hi,
I have been having the following error when I run demultiplex:
```
nid00014(1006)$ demultiplex demux barcodes.csv Lane_1_L1_R1.fastq Lane_1_L1_R2.fastq 
usage: demultiplex [-h] [-v] {guess,demux,match} ...
demultiplex: error: invalid barcodes file format
```
The file barcodes.csv looks like this:
```
nid00014(1009)$ head barcodes.csv
P1004_En TCCCTTGTCTCC TAGGAACTGGCC
P1022_En TCCCTTGTCTCC CTAGCGAACATC
P1019_En TCCCTTGTCTCC GACAGGAGATAG
P1015_En TCCCTTGTCTCC ATTCCTGTGAGT
P1003_En TCCCTTGTCTCC GAGGCTCATCAT
P1002_En TCCCTTGTCTCC TCCTCTGTCGAC
P1013_En TCCCTTGTCTCC CTATTTGCGACA
P1011_En TCCCTTGTCTCC AGTAGAGGGATG
P1009_En TCCCTTGTCTCC CGCAGCGGTATA
P1020_En TCCCTTGTCTCC AATGCCTCAACT

```
I have also tried to use a comma separated file and a tab separated file. Do you know what may have been causing the problem/how to solve it?

Any help will be much appreciated!

Thank you
Maria

**Comment by jfjlaros** [comment]
It seems that you are providing multiple barcodes per sample, the `demux` command does not accept this as described [here](https://demultiplex.readthedocs.io/en/latest/usage.html#illumina-fastq-files). The procedure for working with multiple barcodes is described [here](https://demultiplex.readthedocs.io/en/latest/usage.html#multiple-barcodes).

I hope this helps.

**Comment by majogomezhughes** [comment]
Yes! Thank you! I have one more question though, I don't need to specify if it's the forward or the reverse barcode? Does it matter? The way they are separated in the header is by a '+' so I don't know if that's going to cause further problems?
Thanks!

**Comment by jfjlaros** [comment]
You can select part of a barcode using the `-s` and/or `-e` options. Alternatively, you could treat the barcode pair as one barcode, including the `+` sign. As long as you use the default distance function (i.e., do not use the `-d` option), this should work.

**Comment by gsd050** [comment]
I am getting the same error and I am using single barcodes only

PDW233a,TGACGCCA
PDW233b,CTCTCCAG
PDW274a,TAATTG
PDW274b,CAGATA
As3809a,ATCTCGT
As3809b,GAAGTG
DS1a,GACAACT
DS1b,TAGCGGAT
DS2a,TATTCGCAT
DS2b,CTCGCAA

**Comment by jfjlaros** [comment]
Can you try a white space separator?

**Comment by gsd050** [comment]
it works with .txt file but all reads went to unknown

**Comment by gsd050** [comment]
Just found the head of the file looks like this. Any suggestions

@NB500921:99:H7WV5AFXX:1:11101:18888:1047 1:N:0:0
NAGCAACTTGCAGGTTGGAGAGCATGACGTCTACGTGGTCTCTCCCCTGCCAAAGTGGAGCGCGAGCCCGAGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGAGCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAGGGGGGGGGG
+
#/AAAEEEEEEEEAEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEA<AAEA<EEEEEAE/EEEAE/EAEEEEEEEAEEEEEAEEAAEAAEEE/AEE/AEEA<EAEE/<A</E/<A<A/A<<</<<AA<AAEEEAEEE///6///<<AA<A<6
@NB500921:99:H7WV5AFXX:1:11101:11322:1047 1:N:0:0
NGTTAGCTTGCAGTGGTCAACTCCCTTCCTATCTTGCGGAGCCAATCGTCTGCTACTATTGGCTCGGTGCTACTGGAAAACACCGGCGGATTCAGCCTAAGGAAACAGGCTAAGTGGTCAACAGGTGGTGGTGGTGGTGGGTTGTTGTTGT
+
#AAAAEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEAEEAEEEEEEEEEEEAEEEEEEEE<AAA6EEEAE<66AE<EA<A<EEEEAE<<AAEEAEEEEAE<<A<6<<A<<6A</A/66AEAEEAAEA/
@NB500921:99:H7WV5AFXX:1:11101:7514:1047 1:N:0:0
NGCCTGTGCAGAGAGCCAGAAGTCAGGCGCAGTTGACGGATTCGGTGAGGAAGTGATCCGGCAGTGGTGGCAGATCCTGGCCGCTCACGTGTCAGGCCACACCCTGCTGCTGCGTCCGTCCGAGATCGGAAGAGCGGTTCAGCAGGAATGC

**Comment by jfjlaros** [comment]
There are no barcodes in the header. Perhaps they are somewhere in the reads, or not present at all.

It would be best to contact your sequencing provider. Alternatively, you can have a look at some [suggestions](https://demultiplex.readthedocs.io/en/latest/faq.html) in the FAQ.
