### ISSUE TITLE
Where is the barcode ? 

### ISSUE THREAD

**Issue by dridk** [jfjlaros/demultiplex#9]
Hi,

just a simple question to clarify my mind... 
Is the barcode supposed to be in the label of the read or in the sequence of the read ? 
Because from your data example, the barcode is not in the sequence. It's only as a suffix of the read name => @HWI-ABCDE:0:0:0000:0000#ACTA/1

So, I have no idea how to demultiplex my reads when they looks like this : 

```
@read1
ACTA NNNNNNNNNNNNNNNNNNNNN
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@read2
ACTA NNNNNNNNNNNNNNNNNNNNN
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@read3
ACTA NNNNNNNNNNNNNNNNNNNNN
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

**Comment by jfjlaros** [comment]
Both cases are supported. For barcodes that occur in the reads, see the [relevant](https://demultiplex.readthedocs.io/en/latest/usage.html#other-files) section of the documentation.

I hope this helps.
